---
- name: config_mesos | configuring zookeeper
  template:
    src: "etc/mesos/zk.j2"
    dest: "/etc/mesos/zk"
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in groups[zookeeper_cluster_master_group]

- name: config_mesos | configuring mesos quorom
  template:
    src: "etc/mesos-master/quorom.j2"
    dest: "/etc/mesos-master/quorom"
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname in groups[zookeeper_cluster_master_group]

- name: config_mesos | disabling mesos-slave (on master-nodes)
  service:
    name: "mesos-slave"
    state: stopped
  when: inventory_hostname in groups[zookeeper_cluster_master_group]

- name: config_mesos | setting mesos-slave service to manual (on master-nodes)
  template:
    src: "etc/init/mesos-slave.override.j2"
    dest: "/etc/init/mesos-slave.override"
    owner: root
    group: root
    mode: 0640
  when: inventory_hostname in groups[zookeeper_cluster_master_group]
