---
# handlers file for ansible-mesosphere
- name: restart mesos-master
  service:
    name: "mesos-master"
    state: restarted
    
- name: restart zookeeper
  service:
    name: "zookeeper"
    state: restarted
